# Use root/rootpassword as user/password credentials
version: '3.7'
services:
  mongodb_container:
    container_name: mongdb-container
    image: mongo:latest
    restart: always
    env_file: 
      - .env
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_USERNAME=${MONGO_INITDB_USERNAME}
      - MONGO_INITDB_PASSWORD=${MONGO_INITDB_PASSWORD}
    networks: 
      - mongo-compose-network
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    command: [--auth]
  
  mysqldb:
    container_name: mysql-container
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'aircraft'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE

networks:
  mongo-compose-network:
    driver: bridge